#!/usr/bin/env bash
# Generate language bindings from proto/lucent/v1/*.proto.
#
#   gen-proto.sh [all|py|ts|cpp]   (default: all)
#
# Generated code is NOT checked in (it is gitignored); each toolchain regenerates
# from the protos, which are the single source of truth. C++ is generated by the
# CMake build (cpp/proto/CMakeLists.txt) — this script's `cpp` target only reports
# that. Python uses grpcio-tools (self-contained protoc). TS uses grpc-tools'
# bundled protoc + the ts-proto plugin. Tool versions are pinned (pyproject.toml,
# gateway/package.json) so output is reproducible across machines and CI.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROTO_ROOT="$ROOT/proto"
TARGET="${1:-all}"

gen_py() {
  echo "gen-proto: python -> py/lucent/v1/"
  local out="$ROOT/py"
  rm -rf "$out/lucent/v1"
  mkdir -p "$out/lucent/v1"
  ( cd "$ROOT/py" && uv run python -m grpc_tools.protoc \
      -I "$PROTO_ROOT" \
      --python_out=. --pyi_out=. --grpc_python_out=. \
      "$PROTO_ROOT"/lucent/v1/*.proto )
  touch "$out/lucent/v1/__init__.py"
  echo "gen-proto: python OK"
}

gen_ts() {
  echo "gen-proto: typescript -> gateway/src/gen/"
  local out="$ROOT/gateway/src/gen"
  rm -rf "$out"
  mkdir -p "$out"
  ( cd "$ROOT/gateway" && ./node_modules/.bin/grpc_tools_node_protoc \
      --plugin=protoc-gen-ts_proto=./node_modules/.bin/protoc-gen-ts_proto \
      --ts_proto_out=src/gen \
      --ts_proto_opt=outputServices=grpc-js,esModuleInterop=true,useOptionals=messages,importSuffix=.js \
      -I "$PROTO_ROOT" \
      "$PROTO_ROOT"/lucent/v1/*.proto )
  # Generated output is trusted, not hand-maintained: skip type-checking it so our
  # own code can stay fully strict without generator quirks failing the build.
  for f in "$out"/lucent/v1/*.ts; do
    { echo "// @ts-nocheck"; cat "$f"; } > "$f.tmp" && mv "$f.tmp" "$f"
  done
  echo "gen-proto: typescript OK"
}

gen_cpp() {
  echo "gen-proto: C++ is generated by CMake (cpp/proto/CMakeLists.txt) during the"
  echo "           build; run 'cmake --build --preset dev' to regenerate .pb/.grpc.pb."
}

case "$TARGET" in
  all) gen_py; gen_ts; gen_cpp ;;
  py)  gen_py ;;
  ts)  gen_ts ;;
  cpp) gen_cpp ;;
  *) echo "usage: gen-proto.sh [all|py|ts|cpp]" >&2; exit 2 ;;
esac
